import type { Metadata } from "next";
import * as X from "@/components/xcomponents";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function UnauthPage() {

    return (
        <div className="flex items-center justify-center w-full">
            <div className="flex flex-col gap-8 w-full lg:w-xl items-center justify-center grid-flow-row">
                <X.Container className="w-full text-center">
                    <div className="flex flex-col gap-4">
                        <span className="text-4xl font-semibold">Logout bem-succedido.</span>
                    </div>
                </X.Container>
            </div>
        </div>
    );
}

