import type { Metadata } from "next";
import * as X from "@/components/xcomponents";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ErrorPage() {

    return (
        <div className="flex items-center justify-center w-full">
            <div className="flex flex-col gap-8 w-full lg:w-xl items-center justify-center grid-flow-row">
                <X.Container className="w-full text-center">
                    <div className="flex flex-col gap-4">
                        <span className="text-7xl font-bold">404</span>
                        <span className="text-4xl font-semibold">Algo deu errado...</span>
                    </div>
                </X.Container>
                <X.Link href="/" className="">Voltar para o inicio?</X.Link>
            </div>
        </div>
    );
}

