import type { Metadata } from "next";
import * as X from "@/components/xcomponents";
import { signIn } from "next-auth/react";
import LoginForm from "@/components/auth/loginForm";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Login() {

    return (
        <div className="flex items-center justify-center w-full">
            <LoginForm></LoginForm>
        </div>
    );
}
